--liquibase formatted sql

--changeset mipotter:create_table_sert_core.risks endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables  where owner = upper('${sert_core_schema}') and table_name = 'RISKS';
CREATE TABLE  ${sert_core_schema}.risks (
    risk_id     NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    risk_code   VARCHAR2(250) NOT NULL,
    risk_name   VARCHAR2(250) NOT NULL,
    url         VARCHAR2(250) NOT NULL,
    description VARCHAR2(4000),
    created_by  VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on  TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by  VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on  TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE  ${sert_core_schema}.risks ADD CONSTRAINT risks_pk PRIMARY KEY ( risk_id );
--rollback drop table ${sert_core_schema}.risks;