--liquibase formatted sql

--changeset mipotter:create_table_sert_core.rule_severity endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables  where owner = upper('${sert_core_schema}') and table_name = 'RULE_SEVERITY';
CREATE TABLE  ${sert_core_schema}.rule_severity (
    rule_severity_id   NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    rule_severity_name VARCHAR2(250) NOT NULL,
    rule_severity_key  VARCHAR2(250) NOT NULL,
    seq                NUMBER NOT NULL,
    description        VARCHAR2(4000),
    created_by         VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by         VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on         TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;

ALTER TABLE  ${sert_core_schema}.rule_severity ADD CONSTRAINT rule_severity_pk PRIMARY KEY ( rule_severity_id );

ALTER TABLE  ${sert_core_schema}.rule_severity ADD CONSTRAINT rule_severity_un UNIQUE ( rule_severity_key );
--rollback drop table ${sert_core_schema}.rule_severity;