--liquibase formatted sql

--changeset mipotter:create_table_sert_core.shared_comp_views endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables where owner = '${SERT_BASE_SCHEMA}' and table_name = 'SHARED_COMP_VIEWS';
CREATE TABLE  ${sert_core_schema}.shared_comp_views (
    shared_comp_view_id NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    shared_comp_view    VARCHAR2(250) NOT NULL,
    shared_comp_type    VARCHAR2(250) NOT NULL,
    description         VARCHAR2(4000),
    created_by          VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on          TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL,
    updated_by          VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user),
    updated_on          TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp
)
LOGGING;
ALTER TABLE  ${sert_core_schema}.shared_comp_views ADD CONSTRAINT shared_comp_views_pk PRIMARY KEY ( shared_comp_view_id );

ALTER TABLE  ${sert_core_schema}.shared_comp_views ADD CONSTRAINT shared_comp_views_un UNIQUE ( shared_comp_view );
--rollback drop table ${sert_core_schema}.shared_comp_views;

