--liquibase formatted sql

--changeset mipotter:create_table_sert_core.logs endDelimiter:; runOnChange:true runAlways:false rollbackEndDelimiter:;
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 select count(1) from all_tables  where owner = upper('${sert_core_schema}') and table_name = 'LOGS';
CREATE TABLE  ${sert_core_schema}.logs (
    log_id     NUMBER
        GENERATED BY DEFAULT AS IDENTITY ( START WITH 1 NOCACHE ORDER )
    NOT NULL,
    log_type   VARCHAR2(100) NOT NULL,
    log_key    VARCHAR2(250),
    log        VARCHAR2(4000),
    log_clob   CLOB,
    id         VARCHAR2(250),
    id_col     VARCHAR2(250),
    id_table   VARCHAR2(250),
    created_by VARCHAR2(250) DEFAULT ON NULL coalesce(sys_context('APEX$SESSION', 'APP_USER'),
                                                      user) NOT NULL,
    created_on TIMESTAMP WITH LOCAL TIME ZONE DEFAULT ON NULL systimestamp NOT NULL
)
LOGGING;

ALTER TABLE  ${sert_core_schema}.logs ADD CONSTRAINT logs_pk PRIMARY KEY ( log_id );
--rollback drop table ${sert_core_schema}.logs;